### ISSUE TITLE
home.template setting leads to nullpointer

### ISSUE THREAD

**Issue by WolfgangFahl** [rythmengine/rythmengine#321]
http://rythmengine.org/doc/developer_guide.md

says: home.template can be set via file or string but when I try it with:

```java
    File template=new File("src/test/rythm/test.html");
    Map<String, Object> conf = new HashMap<String, Object>();
    conf.put("home.template", "src/test/rythm");
    RythmEngine engine = new RythmEngine(conf);
    Map<String,Object> rootMap=new HashMap<String,Object>();
    String result=engine.render(template,rootMap);
    System.out.println(result);
```

I get:

```
java.lang.NullPointerException
	at org.rythmengine.resource.TemplateResourceBase.<init>(TemplateResourceBase.java:57)
	at org.rythmengine.resource.FileTemplateResource.<init>(FileTemplateResource.java:52)
	at org.rythmengine.resource.TemplateResourceManager.get(TemplateResourceManager.java:229)
	at org.rythmengine.RythmEngine.getTemplate(RythmEngine.java:963)
	at org.rythmengine.RythmEngine.render(RythmEngine.java:1066)
```

**Comment by WolfgangFahl** [comment]
http://www.simosh.com/article/daejeeaf-where-to-place-rythm-template-files.html seems to have a similar problem

**Comment by greenlaw110** [comment]
Fixed in 1.1.6-SNAPSHOT

**Comment by greenlaw110** [comment]
The issue is incorrect error reporting. It should say `template home not found` instead of an NPE. It's now fixed in 1.1.6-SNAPSHOT, and it will report the correct message:

![image](https://cloud.githubusercontent.com/assets/216930/15453479/ffb93568-205a-11e6-9057-d9db0712705b.png)

Special note about the path `src/test/rythm/test.html` used in this case, even if you created that file, the runtime app will NOT be able to locate that place because it's a relative folder, and runtime will search inside the `target` dir if you run the app with maven. Obviously nothing from your testing dir will get copied into target unless you are running unit testing

**Comment by WolfgangFahl** [comment]
Just checked out things from git - the problem persists. I was assuming if i set home.template that I can also use it. I do not understand your comment about the relative paths not being possible. My assumption was that I can point home.template to any directory that I wish in the file sytem and then use it. At least that's what I would read from the documentation and need for my use case and therefore expect - I am puzzled how complicated this is in comparison to what the needs are.

**Comment by WolfgangFahl** [comment]
home.template.dir works home.template doesn't. You might want to fix the documentation

**Comment by WolfgangFahl** [comment]
Found more quirks of templat handling see "adds another aspect" above.:

1.  When using the extension ".html" html escaping is automatically switched on - Its not clear how to switch of this "feature" which is a bug in my use case
2. When using another extension e.g. ".txt" or macro the @include doesn't work at all ... very strange ...

**Comment by greenlaw110** [comment]
Automatically html escaping on template with '.html' suffix is a [feature](http://rythmengine.org/doc/expression.md#escape), **NOT** a bug.

**Comment by WolfgangFahl** [comment]
Green please do not take this personally. I am talking about my use case where I need to transfer HTML data via SOAP to another system via CDATA sections. If the HTML is escaped in this case it will end up garbled in the target system so I need to be able to switch off html escaping. I have now converted by templates to the extension ".rythm" but had to convince my eclipse to treat the files as html nevertheless. I'd like to know how to switch off the feature.  The link you provided ends up at http://rythmengine.org/doc/transformer which gives "Not found". Please advise - it would be great if you'd modify the source code of the Testcase to make things work.

**Comment by greenlaw110** [comment]
Hi Wolfgang,

I will take time to work on that GithubIssue321 test.

In terms of doc, are you looking for
http://rythmengine.org/doc/builtin_transformer.md#escape0?

Literally to embed something you need "raw" string, instead of escape
string, you go it with template code look like:

<![CDATA[
@myHtml.raw()
]]>


Regards,
Green

**Comment by WolfgangFahl** [comment]
I need the full result of a template to be "raw" not only part of it. So I want to override the assignment of ".html" to be "raw".

**Comment by greenlaw110** [comment]
The turn off the auto escaping for the whole render call
RythmEngine.prepare(ICodeType) api before calling render API. In the case
of the GithubIssue321TestCase, it is:

[image: pasted1]

**Comment by greenlaw110** [comment]
The turn off the auto escaping for the whole render call
`RythmEngine.prepare(ICodeType)` api before calling render API. In the case
of the `GithubIssue321TestCase`, it is:

![image](https://cloud.githubusercontent.com/assets/216930/15464701/2358f7b0-2114-11e6-8078-43844c0e1278.png)

**Comment by greenlaw110** [comment]
Okay found why that `home.template` doesn't work in `GithubIssue321TestCase`:

That test case extends from `TestBase` where you got this bit of code:

![image](https://cloud.githubusercontent.com/assets/216930/15469523/16a2b3e8-212e-11e6-8b40-4a233bcaaddb.png)

And now the system properties got a `home.template.dir` already so your supplied `home.template` will not be evaluated:

![image](https://cloud.githubusercontent.com/assets/216930/15469516/00d71220-212e-11e6-96c7-719d5f24b44a.png)

So the solution is simple, adding a line to remove that setting from System.properties and now the test case pass through:

![image](https://cloud.githubusercontent.com/assets/216930/15469564/5e9292ea-212e-11e6-9faf-631d5b48ced6.png)

**Comment by WolfgangFahl** [comment]
Excellent - this is very helpful
